### ISSUE TITLE
Alternative use of find

### ISSUE THREAD

**Issue by artyom** [lunatic-cat/xxhashdir#2]
Instead of using find like this:

    time find /Applications/Xcode.app -type f -exec xxhsum {} ; > xxhsum.txt

Please also include in README results for

    time find /Applications/Xcode.app -type f -exec xxhsum {} + > xxhsum.txt

**Comment by razum2um** [comment]
Great suggestion, to tell the truth, never used that, thanks. Much better, although still slower, added to the readme

Besides, this implies the executed binary should support varargs (which is true in this case, but not always so, that's why I used to `;`)

Just putting a memory link for future self https://unix.stackexchange.com/a/196917
